### ISSUE TITLE
os module is not imported in the `test_util.py` nor `fa_skeleton_test.py`

### ISSUE THREAD

**Issue by kcho** [pnlbwh/dMRIharmonization#42]
`os` module is not imported in the `test_util.py` nor `fa_skeleton_test.py`
therefore returns error 

```py
Traceback (most recent call last):
  File "../fa_skeleton_test.py", line 209, in <module>
    main()
  File "../fa_skeleton_test.py", line 186, in main
    statFile= os.path.join(self.templatePath, 'meanFAstat.txt')
NameError: name 'os' is not defined
```
https://github.com/pnlbwh/dMRIharmonization/blob/3481ea7aabb17cd048abbfeb4a4707fc7a54d211/lib/tests/fa_skeleton_test.py#L186

**Comment by kcho** [comment]
also in the same line,

https://github.com/pnlbwh/dMRIharmonization/blob/3481ea7aabb17cd048abbfeb4a4707fc7a54d211/lib/tests/fa_skeleton_test.py#L186


`self.templatePath` should be `templatePath`
